name: ubcsalary
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterlab==4.1.6
  - bs4==4.12.3
  - ipython==8.22.2
  - make==4.3
  - matplotlib==3.8.3
  - nltk==3.8.1
  - numpy==1.26.4
  - pandas==2.2.1
  - pypdf==4.2.0
  - pytest==8.1.1
  - regex==2023.12.25
  - scikit-learn==1.4.2
  - sentence-transformers==2.2.2
  - tabulate==0.9.0
  - wordcloud==1.9.3
  - yellowbrick==1.5
  - ipywidgets==8.1.2